# Generated by Django 5.1.2 on 2024-10-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arvrdevice',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visionpro',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
