# Generated by Django 5.1.2 on 2024-10-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_arvrdevice_reserved_at_visionpro_reserved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='arvrdevice',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='visionpro',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
