# Generated by Django 5.1.2 on 2024-10-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arvrdevice',
            name='id',
        ),
        migrations.RemoveField(
            model_name='visionpro',
            name='id',
        ),
        migrations.AlterField(
            model_name='arvrdevice',
            name='serial_number',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='visionpro',
            name='serial_number',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
