# Generated by Django 5.1.2 on 2024-10-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_userreservationrequest_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreservationrequest',
            name='department',
            field=models.CharField(default='temp', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreservationrequest',
            name='reason',
            field=models.TextField(default='cuz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreservationrequest',
            name='role',
            field=models.CharField(default='analyst', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userreservationreturn',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=20),
        ),
    ]
